version: 0.2
phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo pre_build phase...
      - chmod +x gradlew
  build:
    commands:
      - echo build started on `date`
      - ./gradlew assembleDebug
      - ./gradew clean build
      - ./gradlew build --scan
  post_build:
    commands:
      - echo build completed on `date`
artifacts:
  type: zip
  files:
    - 'build/libs/HotelReservation-0.0.1-SNAPSHOT.jar'
  discard-paths: yes